name: CI / CD (Lambda - Lint, Test, Deploy)

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch: {}

permissions:
  contents: read

env:
  AWS_REGION: us-east-1
  PYTHON_VERSION: "3.12"
  ROTATE_FUNC_NAME: rotate-and-deactivate-keys
  PURGE_FUNC_NAME: purge-deactivated-keys
  ARTIFACT_DIR: artifacts
  ROTATE_ZIP: artifacts/rotate_and_deactivate_keys.zip
  PURGE_ZIP: artifacts/purge_deactivated_keys.zip

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint-test-package-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      # -------- LINT & TEST DEPS --------
      - name: Install lint & test deps
        run: |
          python -m pip install --upgrade pip
          pip install ruff==0.6.9 pytest pytest-mock
          # Needed so tests can import boto3 locally (Lambda runtime has it)
          pip install boto3 botocore

      - name: Lint with Ruff
        run: ruff check --output-format=github .

      - name: Clean Python caches
        run: |
          find . -type d -name "__pycache__" -exec rm -rf {} +
          find . -type f -name "*.py[co]" -delete

      # -------- TEST --------
      - name: Run tests
        env:
          PYTHONPATH: ${{ github.workspace }}
          AWS_DEFAULT_REGION: ${{ env.AWS_REGION }}
        run: pytest -q

      - name: Prepare artifact dir
        run: |
          rm -rf "${{ env.ARTIFACT_DIR }}"
          mkdir -p "${{ env.ARTIFACT_DIR }}"

      # -------- PACKAGE: rotate --------
      - name: Package rotate_and_deactivate_keys
        working-directory: lambdas/rotate_and_deactivate_keys
        run: |
          set -euo pipefail
          rm -rf build
          mkdir -p build
          cp app.py build/
          if [ -s requirements.txt ]; then
            pip install -r requirements.txt -t build
          fi
          (cd build && zip -r "${GITHUB_WORKSPACE}/${{ env.ROTATE_ZIP }}" .)

      # -------- PACKAGE: purge --------
      - name: Package purge_deactivated_keys
        working-directory: lambdas/purge_deactivated_keys
        run: |
          set -euo pipefail
          rm -rf build
          mkdir -p build
          cp app.py build/
          if [ -s requirements.txt ]; then
            pip install -r requirements.txt -t build
          fi
          (cd build && zip -r "${GITHUB_WORKSPACE}/${{ env.PURGE_ZIP }}" .)

      - name: Show artifacts
        run: |
          ls -lah "${{ env.ARTIFACT_DIR }}"
          test -s "${{ env.ROTATE_ZIP }}" || (echo "Missing rotate zip" && exit 1)
          test -s "${{ env.PURGE_ZIP }}"  || (echo "Missing purge zip" && exit 1)

      # -------- AUTH (STATIC KEYS) --------
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      # -------- PRE-FLIGHT SECRET CHECKS --------
      - name: Check required secrets
        shell: bash
        env:
          ROTATE_LAMBDA_ROLE_ARN: ${{ secrets.ROTATE_LAMBDA_ROLE_ARN }}
          PURGE_LAMBDA_ROLE_ARN: ${{ secrets.PURGE_LAMBDA_ROLE_ARN }}
          TARGET_USERNAME:        ${{ secrets.TARGET_USERNAME }}
          SECRET_NAME:            ${{ secrets.SECRET_NAME }}
          SNS_TOPIC_ARN:          ${{ secrets.SNS_TOPIC_ARN }}
          SECRET_JSON_KEY:        ${{ secrets.SECRET_JSON_KEY }}
        run: |
          set -euo pipefail
          : "${ROTATE_LAMBDA_ROLE_ARN:?Missing secret ROTATE_LAMBDA_ROLE_ARN}"
          : "${PURGE_LAMBDA_ROLE_ARN:?Missing secret PURGE_LAMBDA_ROLE_ARN}"
          : "${TARGET_USERNAME:?Missing secret TARGET_USERNAME}"
          : "${SECRET_NAME:?Missing secret SECRET_NAME}"
          : "${SNS_TOPIC_ARN:?Missing secret SNS_TOPIC_ARN}"
          echo "All required secrets present."

      # -------- CREATE IF MISSING / DEPLOY: ROTATE --------
      - name: Ensure ${{ env.ROTATE_FUNC_NAME }} exists
        shell: bash
        run: |
          if ! aws lambda get-function --function-name "${ROTATE_FUNC_NAME}" >/dev/null 2>&1; then
            aws lambda create-function \
              --function-name "${ROTATE_FUNC_NAME}" \
              --runtime python3.12 \
              --handler app.lambda_handler \
              --role "${{ secrets.ROTATE_LAMBDA_ROLE_ARN }}" \
              --timeout 60 \
              --memory-size 256 \
              --zip-file fileb://"${{ env.ROTATE_ZIP }}"
          fi

      - name: Deploy ${{ env.ROTATE_FUNC_NAME }}
        run: |
          aws lambda update-function-code \
            --function-name "${ROTATE_FUNC_NAME}" \
            --zip-file fileb://"${{ env.ROTATE_ZIP }}"
          aws lambda update-function-configuration \
            --function-name "${ROTATE_FUNC_NAME}" \
            --environment "Variables={TARGET_USERNAME=${{ secrets.TARGET_USERNAME }},SECRET_NAME=${{ secrets.SECRET_NAME }},SNS_TOPIC_ARN=${{ secrets.SNS_TOPIC_ARN }},SECRET_JSON_KEY=${{ secrets.SECRET_JSON_KEY || 'current' }}}"

      # -------- CREATE IF MISSING / DEPLOY: PURGE --------
      - name: Ensure ${{ env.PURGE_FUNC_NAME }} exists
        shell: bash
        run: |
          if ! aws lambda get-function --function-name "${PURGE_FUNC_NAME}" >/dev/null 2>&1; then
            aws lambda create-function \
              --function-name "${PURGE_FUNC_NAME}" \
              --runtime python3.12 \
              --handler app.lambda_handler \
              --role "${{ secrets.PURGE_LAMBDA_ROLE_ARN }}" \
              --timeout 60 \
              --memory-size 256 \
              --zip-file fileb://"${{ env.PURGE_ZIP }}"
          fi

      - name: Deploy ${{ env.PURGE_FUNC_NAME }}
        run: |
          aws lambda update-function-code \
            --function-name "${PURGE_FUNC_NAME}" \
            --zip-file fileb://"${{ env.PURGE_ZIP }}"
          aws lambda update-function-configuration \
            --function-name "${PURGE_FUNC_NAME}" \
            --environment "Variables={TARGET_USERNAME=${{ secrets.TARGET_USERNAME }}}"
