name: CI / CD (Terraform + Python)

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read

env:
  AWS_REGION: us-east-1

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint-test-deploy:
    name: Lint, Test & Deploy Lambdas
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff pytest

      - name: Lint with Ruff
        run: ruff check --output-format=github .

      - name: Run tests
        env:
          PYTHONPATH: ${{ github.workspace }}
        run: pytest -q

      - name: Package rotate-and-deactivate-keys
        run: |
          cd lambdas/rotate_and_deactivate_keys
          zip -r ../../rotate-and-deactivate-keys.zip .
          cd ../..

      - name: Package purge-deactivated-keys
        run: |
          cd lambdas/purge_deactivated_keys
          zip -r ../../purge-deactivated-keys.zip .
          cd ../..

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Deploy rotate-and-deactivate-keys
        run: |
          aws lambda get-function --function-name rotate-and-deactivate-keys \
            || aws lambda create-function \
              --function-name rotate-and-deactivate-keys \
              --runtime python3.12 \
              --role ${{ secrets.ROTATE_FUNC_ROLE_ARN }} \
              --handler app.lambda_handler \
              --zip-file fileb://rotate-and-deactivate-keys.zip
          aws lambda update-function-code \
            --function-name rotate-and-deactivate-keys \
            --zip-file fileb://rotate-and-deactivate-keys.zip

      - name: Deploy purge-deactivated-keys
        run: |
          aws lambda get-function --function-name purge-deactivated-keys \
            || aws lambda create-function \
              --function-name purge-deactivated-keys \
              --runtime python3.12 \
              --role ${{ secrets.PURGE_FUNC_ROLE_ARN }} \
              --handler app.lambda_handler \
              --zip-file fileb://purge-deactivated-keys.zip
          aws lambda update-function-code \
            --function-name purge-deactivated-keys \
            --zip-file fileb://purge-deactivated-keys.zip
