name: Infra Provisioning (Terraform with Remote Backend)

on:
  push:
    branches: ["main"]
    paths:
      - "terraform/**"
      - ".github/workflows/infra-provision.yml"
  pull_request:
    branches: ["main"]
    paths:
      - "terraform/**"
      - ".github/workflows/infra-provision.yml"
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment (used for workflow_dispatch and shown in env badge)"
        required: true
        default: "dev"
        type: choice
        options: ["dev", "stage", "prod"]
      action:
        description: "Terraform action"
        required: true
        default: "plan"
        type: choice
        options: ["plan", "apply"]

permissions:
  contents: read

env:
  TF_VERSION: "1.8.5"
  TF_WORKING_DIR: terraform
  TF_STATE_KEY_PREFIX: key-rotation

jobs:
  lint-validate:
    name: Lint & Validate
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.TF_WORKING_DIR }}
    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Terraform Init (S3 backend)
        run: |
          terraform init -input=false \
            -backend-config="bucket=${{ secrets.TF_STATE_BUCKET }}" \
            -backend-config="key=${{ env.TF_STATE_KEY_PREFIX }}/$([[ '${{ github.event_name }}' == 'push' ]] && echo dev || echo ${{ github.event.inputs.environment || 'dev' }}).tfstate" \
            -backend-config="region=${{ secrets.AWS_REGION }}" \
            -backend-config="dynamodb_table=${{ secrets.TF_STATE_TABLE }}" \
            -backend-config="encrypt=true"

      # Normalize & write fmt so fmt never causes a red build
      - name: Normalize line endings for .tf/.tfvars
        run: |
          sudo apt-get update && sudo apt-get install -y dos2unix
          git ls-files '*.tf' '*.tfvars' | xargs -I{} dos2unix {}

      - name: Terraform fmt (write)
        run: terraform fmt -recursive

      - name: Terraform Format Check
        run: terraform fmt -check -recursive

      - name: Terraform Validate
        run: terraform validate

  plan:
    name: Terraform Plan
    needs: [lint-validate]
    if: >
      github.event_name == 'pull_request' ||
      (github.event_name == 'workflow_dispatch' && github.event.inputs.action == 'plan')
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.TF_WORKING_DIR }}
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Terraform Init (S3 backend)
        run: |
          terraform init -input=false \
            -backend-config="bucket=${{ secrets.TF_STATE_BUCKET }}" \
            -backend-config="key=${{ env.TF_STATE_KEY_PREFIX }}/${{ github.event.inputs.environment || 'dev' }}.tfstate" \
            -backend-config="region=${{ secrets.AWS_REGION }}" \
            -backend-config="dynamodb_table=${{ secrets.TF_STATE_TABLE }}" \
            -backend-config="encrypt=true"

      # fail fast if secrets not set (avoids empty -var values)
      - name: Check required secrets
        shell: bash
        env:
          TARGET_USERNAME: ${{ secrets.TARGET_USERNAME }}
          SECRET_NAME:     ${{ secrets.SECRET_NAME }}
          SECRET_JSON_KEY: ${{ secrets.SECRET_JSON_KEY }}
        run: |
          set -euo pipefail
          : "${TARGET_USERNAME:?Missing secret TARGET_USERNAME}"
          : "${SECRET_NAME:?Missing secret SECRET_NAME}"
          echo "All required secrets present."

      - name: Terraform Plan
        run: |
          terraform plan -input=false -out=tfplan.bin \
            -var="aws_region=${{ secrets.AWS_REGION }}" \
            -var="target_username=${{ secrets.TARGET_USERNAME }}" \
            -var="secret_name=${{ secrets.SECRET_NAME }}" \
            -var="secret_json_key=${{ secrets.SECRET_JSON_KEY || 'current' }}"
          terraform show -no-color tfplan.bin > tfplan.txt

      - uses: actions/upload-artifact@v4
        with:
          name: tfplan-${{ github.run_id }}
          path: ${{ env.TF_WORKING_DIR }}/tfplan.txt

  apply:
    name: Terraform Apply
    needs: [lint-validate]
    # FIX: run on workflow_dispatch with action=apply OR push to main (auto-apply dev)
    if: >
      (github.event_name == 'workflow_dispatch' && github.event.inputs.action == 'apply') ||
      (github.event_name == 'push' && github.ref == 'refs/heads/main')
    runs-on: ubuntu-latest
    # For push->main we pin environment to 'dev'. For workflow_dispatch we respect the input.
    environment:
      name: ${{ github.event_name == 'push' && 'dev' || github.event.inputs.environment || 'dev' }}
    defaults:
      run:
        working-directory: ${{ env.TF_WORKING_DIR }}
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Terraform Init (S3 backend)
        run: |
          terraform init -input=false \
            -backend-config="bucket=${{ secrets.TF_STATE_BUCKET }}" \
            -backend-config="key=${{ env.TF_STATE_KEY_PREFIX }}/$([[ '${{ github.event_name }}' == 'push' ]] && echo dev || echo ${{ github.event.inputs.environment || 'dev' }}).tfstate" \
            -backend-config="region=${{ secrets.AWS_REGION }}" \
            -backend-config="dynamodb_table=${{ secrets.TF_STATE_TABLE }}" \
            -backend-config="encrypt=true"

      # fail fast if secrets not set
      - name: Check required secrets
        shell: bash
        env:
          TARGET_USERNAME: ${{ secrets.TARGET_USERNAME }}
          SECRET_NAME:     ${{ secrets.SECRET_NAME }}
          SECRET_JSON_KEY: ${{ secrets.SECRET_JSON_KEY }}
        run: |
          set -euo pipefail
          : "${TARGET_USERNAME:?Missing secret TARGET_USERNAME}"
          : "${SECRET_NAME:?Missing secret SECRET_NAME}"
          echo "All required secrets present."

      - name: Terraform Apply
        run: |
          terraform apply -input=false -auto-approve \
            -var="aws_region=${{ secrets.AWS_REGION }}" \
            -var="target_username=${{ secrets.TARGET_USERNAME }}" \
            -var="secret_name=${{ secrets.SECRET_NAME }}" \
            -var="secret_json_key=${{ secrets.SECRET_JSON_KEY || 'current' }}"
