name: Infra Provisioning (Bootstrap + Terraform)

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment (dev, stage, prod)"
        required: true
        default: "dev"
        type: choice
        options: ["dev","stage","prod"]
      action:
        description: "Terraform action"
        required: true
        default: "plan"
        type: choice
        options: ["plan","apply"]

permissions:
  contents: read

env:
  TF_VERSION: "1.8.5"
  TF_BACKEND_DIR: terraform-backend-bootstrap
  TF_WORKING_DIR: terraform
  TF_STATE_KEY_PREFIX: key-rotation

jobs:
  bootstrap:
    runs-on: ubuntu-latest
    if: github.event.inputs.environment == 'dev' # bootstrap once in dev
    defaults:
      run:
        working-directory: ${{ env.TF_BACKEND_DIR }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Terraform Init (local)
        run: terraform init -input=false

      - name: Terraform Apply (backend)
        if: github.event.inputs.action == 'apply'
        run: terraform apply -auto-approve -input=false \
          -var="state_bucket_name=${{ secrets.TF_STATE_BUCKET }}" \
          -var="lock_table_name=${{ secrets.TF_STATE_TABLE }}" \
          -var="aws_region=${{ secrets.AWS_REGION }}"

  provision:
    runs-on: ubuntu-latest
    needs: [bootstrap]
    defaults:
      run:
        working-directory: ${{ env.TF_WORKING_DIR }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Terraform Init (remote backend)
        run: |
          terraform init -input=false \
            -backend-config="bucket=${{ secrets.TF_STATE_BUCKET }}" \
            -backend-config="key=${{ env.TF_STATE_KEY_PREFIX }}/${{ github.event.inputs.environment }}.tfstate" \
            -backend-config="region=${{ secrets.AWS_REGION }}" \
            -backend-config="dynamodb_table=${{ secrets.TF_STATE_TABLE }}" \
            -backend-config="encrypt=true"

      - name: Terraform Format
        run: terraform fmt -check -recursive

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        if: github.event.inputs.action == 'plan'
        run: terraform plan -input=false -out=tfplan.bin

      - name: Terraform Apply
        if: github.event.inputs.action == 'apply'
        run: terraform apply -input=false -auto-approve
